{%- extends 'hide.tpl' -%}
{%- block body -%}

---
layout: post
{%- for k in ['keywords', 'description', 'title', 'toc', 'badges', 'comments', 'categories', 'hide', 'draft', 'nb_path'] %}
{% if k == "summary" and "description" not in resources %}description{% else %}{{ k }}{% endif %}: {{ resources[k] }}
{%- endfor %}
---

<!--
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: {{ resources.nb_path }}
-->

<div class="container" id="notebook-container">

  <p><a href="https://colab.research.google.com/github/codescv/codescv.github.io/blob/main/{{resources['nb_path']}}"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="" /></a></p>

  {{ super()  }}

</div>
{%- endblock body %}
